// autogenerated - uart_rx_wtb.v

module uart_rx_wtb;

  // Instantiation of module uart_rx
  reg         CLK;
  reg         RST_N;
  reg         RX;
  wire  [7:0] RX_DATA;
  wire        RX_DONE;
  wire        RX_VALID;

  uart_rx #(
      .CLK_FREQ(96000),
      .BAUD(9600)
  ) dut (
      .clk(CLK),
      .rst_n(RST_N),
      .rx(RX),
      .rx_data(RX_DATA),
      .done(RX_DONE),
      .valid(RX_VALID)
  );

endmodule 