// autogenerated - uart_rx_wtb.v

module uart_rx_wtb;

  // Instantiation of module uart_rx
  reg         clk;
  reg         rst_n;
  reg         rx;
  wire  [7:0] rx_data;
  wire        rx_done;
  wire        rx_valid;

  uart_rx #(
      .CLK_FREQ(30_000_000),
      .BAUD(9600)
  ) dut (
      .clk(clk),
      .rst_n(rst_n),
      .rx(rx),
      .rx_data(rx_data),
      .done(rx_done),
      .valid(rx_valid)
  );

endmodule 