// autogenerated - uart_rx_wtb.v

module uart_tx_wtb;

  // Instantiation of module uart_rx
  reg         clk;
  reg         rst_n;
  reg         tx_start;
  reg  [7:0]  tx_data;
  wire        tx; 
  wire        busy;
  wire        done;

  uart_tx #(
      .CLK_FREQ(30_000_000),
      .CYCLES_PER_BIT(3125)
  ) dut (
      .clk(clk),
      .rst_n(rst_n),
      .tx(tx),
      .tx_start(tx_start),
      .tx_data(tx_data),
      .busy(busy),
      .done(done)
  );

endmodule